Customer/urls.py
from django.urls import path, register_converter, include
from Core.converters import DateConverter
register_converter(DateConverter, 'date')

from .views import dues, goc, customer, ledger

urlpatterns = [
    # Group of Company
    path('groupofcompany/', include([
        path('list/', goc.GroupofCompaniesView.as_view(), name="groupofcompanies"),
        path('<int:pk>/', include([
            path('update/',  goc.GroupofCompanyUpdateView.as_view(), name="update-groupofcompany"),
            path('delete/',  goc.GroupofCompanyDeleteView.as_view(), name="delete-groupofcompany"),
            path('status/',  goc.change_goc_status, name="change-goc-status"),
            path('dues/', include([
                # 
            ])),
            path('<date:date>/<int:goc>/mark-baddebt/', dues.markBaddebt, name='mark-baddebt'),
            path('<date:date>/<int:goc>/<int:unmark>/unmark-baddebt/', dues.markBaddebt, name='mark-baddebt'),
        ])),
    ])),

    # Customer
    path('', include([
        path('list/',  customer.CustomerView.as_view(), name="customers"),
        path('<int:pk>/', include([
            path('update/',  customer.CustomerUpdateView.as_view(), name="update-customer"),
            path('delete/',  customer.CustomerDeleteView.as_view(), name="delete-customer"),
            path('status/',  customer.change_cust_status, name="change-cust-status"),
            path('<date:date>/mark-baddebt/', dues.markBaddebt, name='mark-baddebt'),
            path('<date:date>/<int:unmark>/unmark-baddebt/', dues.markBaddebt, name='mark-baddebt'),
        ])),
        path('dues/<date:date>/', include([
            path('', dues.CustomerDueView.as_view(), name='customer-due'),
            path('update/', dues.customerBalanceFormsetView, name='customer-due-update'),
        ])),
    ])),

    # Due Collection
    path('duecollection/<date:date>/', include([
        path('create/', dues.DueCollectionCreateView.as_view(), name="create-duecollection"),
        path('<int:pk>/', include([
            path('update/', dues.DueCollectionUpdateView.as_view(), name='update-duecollection'),
            path('delete/', dues.DueCollectionDeleteView.as_view(), name='delete-duecollection'),
        ])),
    ])),

    # Due Sell
    path('duesell/<date:date>/',  include([
        path('create/', dues.DueSellCreateView.as_view(), name="create-duesell"),
        path('<int:pk>/update/', dues.DueSellUpdateView.as_view(), name="update-duesell"),
        path('<int:pk>/delete/', dues.DueSellDeleteView.as_view(), name="delete-duesell"),
    ])),

    # Ledger
    path('ledger/', include([
        path('<date:date>/', include([
            path('topsheet/', ledger.CustomerTopSheet.as_view(), name='customer-topsheet'),
            path('customer/<int:customer>/', ledger.CustomerLedger.as_view(), name='customer-ledger'),
            path('goc/<int:customer>/', ledger.GroupofCompanyLedger.as_view(), name='groupofcompany-ledger'),
        ])),
    ])),
]

FillingStation/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
# import debug_toolbar

from .views import HomeView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('Account.urls')),
    path('settings/', include("Core.urls")),
    path('', HomeView.as_view(), name="home"), # Currently redirects to 'daily-transactions'
    path('transactions/', include("Transaction.urls")),
    path('ledgers/', include("Ledger.urls")),
    path('loan/', include("Loan.urls")),
    path('customer/', include("Customer.urls")),
    path('income-expenditure/', include("IncomeExpenditure.urls")),
    path('owner/', include("Owner.urls")),
    path('product/', include("Product.urls")),
    path('documentation/', include("Documentation.urls")),
]

if settings.DEBUG:
    # urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]
    
    # Serving static files during development (automatically does this)
    # If you don’t have django.contrib.staticfiles in INSTALLED_APPS
    # urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

    # Serving files uploaded by a user during development
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Loan/urls.py
from django.urls import path, register_converter, include
from Core.converters import DateConverter
register_converter(DateConverter, 'date')

from .views import (
    LoanView, BorrowedLoanDetailView, LendedLoanDetailView,
    LenderView, LenderUpdateView, 
    BorrowerView, BorrowerUpdateView,
    BorrowLoanCreateView, BorrowLoanUpdateView, BorrowLoanDeleteView,
    RefundBorrowedLoanCreateView, RefundBorrowedLoanUpdateView, RefundBorrowedLoanDeleteView,
    LendLoanCreateView, LendLoanUpdateView, LendLoanDeleteView,
    RefundLendedLoanCreateView, RefundLendedLoanUpdateView, RefundLendedLoanDeleteView,
    )

urlpatterns = [
    path('', LoanView.as_view(), name='loan-dashboard'),
    path('lender/', include([
        path('', LenderView.as_view(), name='lender'),
        path('<int:pk>/', include([
            path('detail/', BorrowedLoanDetailView.as_view(), name='borrowed-loan-detail'),
            path('update/', LenderUpdateView.as_view(), name='update-lender'),
        ])),
    ])),
    
    path('borrower/', include([
        path('', BorrowerView.as_view(), name='borrower'),
        path('<int:pk>/', include([
            path('detail/', LendedLoanDetailView.as_view(), name='lended-loan-detail'),
            path('update/', BorrowerUpdateView.as_view(), name='update-borrower'),
        ])),
    ])),
    path('borrowed-loan/', include([
        path('new/', BorrowLoanCreateView.as_view(), name='create-borrowed-loan'),
        path('<int:loan_pk>/', include([
            path('update/', BorrowLoanUpdateView.as_view(), name='update-borrowed-loan'),
            path('delete/', BorrowLoanDeleteView.as_view(), name='delete-borrowed-loan'),
            path('refund/', include([
                path('new/', RefundBorrowedLoanCreateView.as_view(), name='create-refund-borrowed-loan'),
                path('<int:pk>/', include([
                    path('update/', RefundBorrowedLoanUpdateView.as_view(), name='update-refund-borrowed-loan'),
                    path('delete/', RefundBorrowedLoanDeleteView.as_view(), name='delete-refund-borrowed-loan'),
                ])),
            ])),
        ])),
    ])),
    
    path('lended-loan/', include([
        path('new/', LendLoanCreateView.as_view(), name='create-lended-loan'),
        path('<int:loan_pk>/', include([
            path('update/', LendLoanUpdateView.as_view(), name='update-lended-loan'),
            path('delete/', LendLoanDeleteView.as_view(), name='delete-lended-loan'),
            path('refund/', include([
                path('new/', RefundLendedLoanCreateView.as_view(), name='create-refund-lended-loan'),
                path('<int:pk>/', include([
                    path('update/', RefundLendedLoanUpdateView.as_view(), name='update-refund-lended-loan'),
                    path('delete/', RefundLendedLoanDeleteView.as_view(), name='delete-refund-lended-loan'),
                ])),
            ])),
        ])),
    ])),
]

Customer/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
from django.db.models import Sum

from Product.models import Product, SellingRate, Sell
from .choices import customer_type, INDIVIDUAL, GROUP
from Transaction.functions import last_balance_date
from Core.functions import first_date_of_month

class GroupofCompany(models.Model):
    name = models.CharField(max_length=255, verbose_name="নাম")
    # সক্রিয় করলে customer dropdown list এ দেখাবে
    active = models.BooleanField(default=True, verbose_name='সক্রিয়')
    date_created = models.DateField(default=last_balance_date)
    serial = models.SmallIntegerField(default=0, verbose_name="ক্রম")
    active = models.BooleanField(default=True, verbose_name='সক্রিয়')

    class Meta:
        ordering = ['serial']

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse("groupofcompanies")

class Customer(models.Model):
    name        = models.CharField(max_length=255, verbose_name="নাম", unique=True)
    short_name  = models.CharField(max_length=25, verbose_name="সংক্ষিপ্ত নাম", null=True, blank=True)
    cust_type   = models.CharField(max_length=20, verbose_name="ধরণ", choices=customer_type, default=INDIVIDUAL)
    group       = models.ForeignKey(GroupofCompany, on_delete=models.SET_NULL, null=True, blank=True, verbose_name="গ্রুপ")
    mobile      = models.CharField(max_length=11, null=True, blank=True, verbose_name="মোবাইল")
    serial      = models.SmallIntegerField(default=0, verbose_name="ক্রম")
    # সক্রিয় করলে customer dropdown list এ দেখাবে
    active      = models.BooleanField(default=True, verbose_name='সক্রিয়')
    date_created= models.DateField(default=last_balance_date)

    class Meta:
        ordering = ['-active','cust_type','group','serial','name']
        get_latest_by = ['date_created']
    
    def get_next_serial(self):
        max_serial = Customer.objects.aggregate(models.Max('serial'))['serial__max']
        if max_serial is None:
            return 1
        else:
            return max_serial + 1

    def __str__(self):
        txt = self.name
        if self.group: txt += f" ({self.group})"
        return txt
    
    def get_absolute_url(self):
        return reverse("customers")

class DueSell(models.Model):
    date = models.DateField(default=last_balance_date, verbose_name="তারিখ")
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, null=True, verbose_name="ক্রেতা", 
        limit_choices_to={'active':True})
    product = models.ForeignKey(Product, default=1, on_delete=models.SET_NULL, null=True, verbose_name="মাল", 
        limit_choices_to={'active':True})
    quantity = models.FloatField(default=1, verbose_name="পরিমাণ")
    rate = models.FloatField(default=0.0, verbose_name="দর")
    selling_rate = models.ForeignKey(SellingRate, null=True, on_delete=models.SET_NULL)
    price = models.FloatField(null=True, blank=False, verbose_name="মোট")
    sell = models.OneToOneField(Sell, on_delete=models.SET_NULL, null=True, verbose_name='বিক্রয়')

    class Meta:
        ordering = ['-date','customer','product__category','product__name']
        get_latest_by = ['date']

    def __str__(self):
        return f"DueSell: {self.date} - {self.customer} - {self.product} - {self.quantity} Ltr. - {self.price} Tk."
    
    def get_absolute_url(self):
        return reverse('create-duesell', kwargs={'date':self.date})
    
    def save(self, *args, **kwargs):
        self.rate = self.selling_rate.amount
        self.price = self.rate * self.quantity
        super().save(*args, **kwargs)
    
class DueCollection(models.Model):
    date = models.DateField(default=last_balance_date, verbose_name="তারিখ")
    customer = models.ForeignKey(to=Customer, on_delete=models.SET_NULL, null=True, verbose_name="ক্রেতা", 
        limit_choices_to={'active':True})
    amount = models.FloatField(null=True, blank=False, verbose_name="টাকা")

    class Meta:
        ordering = ['-date']
        get_latest_by = ['date']
    
    @property
    def remaining_due(self):
        from .functions import get_remaining_due
        from Core.functions import first_date_of_month
        from_date = first_date_of_month(self.date)
        due,bad_debt = get_remaining_due(from_date,self.date,self.customer)
        return due

    def __str__(self):
        return f"DueCollection: {self.date} - {self.customer} - {self.amount}"
    
    def get_absolute_url(self):
        return reverse('daily-transactions', kwargs={'date':self.date})


# Balance should contain Initial balance.
class BaseCustomerDue(models.Model):
    date    = models.DateField(default=last_balance_date, verbose_name="তারিখ")
    amount  = models.FloatField(null=True, blank=False, verbose_name="পরিমাণ")
    bad_debt= models.BooleanField(default=False, verbose_name="অনিশ্চিত")

    class Meta:
        abstract = True
        ordering = ['-date','customer__serial']
        get_latest_by = ['date','customer__serial']
    
    # @property
    # def due_sells(self):
    #     if isinstance(self, CustomerDue):
    #         queryset = DueSell.objects.filter(customer=self.customer,date=self.date)
    #     else: 
    #         queryset = DueSell.objects.filter(customer__group=self.customer,date=self.date)
    #     return queryset
    
    # @property
    # def due_sells_amount(self):
    #     queryset = self.due_sells
    #     return queryset.aggregate(Sum('price'))['price__sum'] if queryset else 0
    
    # @property
    # def due_collections(self):
    #     if isinstance(self, CustomerDue):
    #         queryset = DueCollection.objects.filter(customer=self.customer,date=self.date)
    #     else: 
    #         queryset = DueCollection.objects.filter(customer__group=self.customer,date=self.date)
    #     return queryset
    
    # @property
    # def due_collections_amount(self):
    #     queryset = self.due_collections
    #     return queryset.aggregate(Sum('amount'))['amount__sum'] if queryset else 0
    
    # @property
    # def current_due(self):
    #     return self.amount + self.due_sells_amount - self.due_collections_amount

    def __str__(self):
        output = f"{self.date} {self.customer} : {self.amount}"
        if self.bad_debt: output += " অনিশ্চিত"
        return output
    
class CustomerDue(BaseCustomerDue):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE, verbose_name="ক্রেতা",
                limit_choices_to={'cust_type': INDIVIDUAL})
    
    def get_absolute_url(self):
        return reverse("customer-ledger", kwargs={"pk": self.pk})

class GroupofCompanyDue(BaseCustomerDue):
    customer = models.ForeignKey(GroupofCompany, on_delete=models.CASCADE, verbose_name="ক্রেতা")

    # @property
    # def sub_company_due(self):
    #     customers = Customer.objects.filter(group=self.customer)
    #     data = []
    #     for cust in customers:
    #         due_sells = self.due_sells.filter(customer=cust)
    #         data.append({
    #             'customer': cust,
    #             'duesell_amount': due_sells.aggregate(Sum('price'))['price__sum'] or None,
    #             'due_sells': due_sells
    #         })
    #     return data
    
    def get_absolute_url(self):
        return reverse("groupofcompany-balance")

Customer/views/customer.py
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required

from Core.mixins import RedirectMixin
from Customer.models import Customer
from Customer.forms import CustomerForm

from django.views.generic import ListView
from django.views.generic.edit import CreateView, DeleteView, UpdateView

# Customer
class CustomerView(RedirectMixin, CreateView, ListView):
    model = Customer
    form_class = CustomerForm
    template_name = 'Customer/customers.html'
    success_url = '.'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['container_class'] = 'hidden'
        return context

class CustomerUpdateView(RedirectMixin, UpdateView, ListView):
    model = Customer
    fields = ['name','short_name','cust_type','group','mobile','serial']
    template_name = 'Customer/customers.html'
    success_url = reverse_lazy('customers')

class CustomerDeleteView(RedirectMixin, DeleteView):
    model = Customer
    success_url = reverse_lazy('customers')

@login_required
def change_cust_status(requst, pk):
    cust = Customer.objects.get(pk=pk)
    cust.active = not cust.active
    cust.save()
    return redirect('customers')

Customer/views/goc.py
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy

from django.views.generic import ListView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from Customer.models import GroupofCompany
from Core.mixins import RedirectMixin

# Group of companies
class GroupofCompaniesView(RedirectMixin, CreateView, ListView):
    model = GroupofCompany
    fields = ['name','active']
    template_name = 'Customer/groupofcompanies.html'
    success_url = '.'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['container_class'] = 'hidden'
        return context

class GroupofCompanyUpdateView(RedirectMixin, UpdateView, ListView):
    model = GroupofCompany
    fields = ['name','active']
    template_name = 'Customer/groupofcompanies.html'
    success_url = reverse_lazy('groupofcompanies')

class GroupofCompanyDeleteView(RedirectMixin, DeleteView):
    model = GroupofCompany
    success_url = reverse_lazy('groupofcompanies')

@login_required
def change_goc_status(requst, pk):
    goc = GroupofCompany.objects.get(pk=pk)
    goc.active = not goc.active
    goc.save()
    return redirect('groupofcompanies')

Customer/templates/Customer/customer_confirm_delete.html
{% extends 'base.html' %}
{% block title %}Delete Customer{% endblock title %}
{% block main %}

<h4>আপনি নিশ্চিত? "{{object}}" নামক হিসাবটি ডিলিট করা হচ্ছে।</h4>
<p>উক্ত দেনাদারের সকল হিসাব ডিলিট হয়ে যাবে।</p>

<form method="post">
    {% csrf_token %}
    <a href="{% url 'customers' %}" class="btn btn-primary">না, ফেরত আসুন</a>
    <input type="submit" value="হ্যা, ডিলিট করুন" class="btn btn-danger">
</form>

{% endblock main %}

Customer/templates/Customer/customers.html
{% extends 'base.html' %}
{% block title %}ক্রেতা{% endblock title %}
{% block style %}
<style>
    .hidden {
        display: none;
    }
    #add-form {
        font-size: 2rem;
    }
</style>
{% endblock style %}
{% block main %}

{% load extra_tags %}
{% load bootstrap5 %}

<h3 class="d-print-none">ক্রেতা
    <i class="bi bi-plus-circle btn p-0" id="add-form"></i>
</h3>
<div id="form-container" class="{{container_class}}">
    <form method="post" class="row mb-3">
        {% csrf_token %}
        <div class="col-md-6">{% bootstrap_field form.name layout='horizontal' %}</div>
        <div class="col-md-6">{% bootstrap_field form.short_name layout='horizontal' %}</div>
        <div class="col-md-6">{% bootstrap_field form.cust_type layout='horizontal' %} </div>
        <div class="col-md-6">{% bootstrap_field form.group layout='horizontal' %}</div>
        <div class="col-md-6">{% bootstrap_field form.mobile layout='horizontal' field_class='eng col-md-9' %}</div>
        <div class="col-md-6">{% bootstrap_field form.serial layout='horizontal' field_class='eng col-md-9' %}</div>
        <div class="col-12 nowrap text-center eng">
            {% bootstrap_button 'Save' button_type='submit' button_class='btn-success' %}
            <a href="{% url 'customers' %}" class="btn btn-secondary">Cancel</a>
        </div>
    </form>
</div>

<table class="table table-sm table-striped table-bordered text-center">
    <caption>
        {% include 'org_name.html' %}
        <h4>দেনাদার/ক্রেতা তালিকা</h4>
    </caption>
    <thead>
        <tr>
            <th>#</th>
            <th>নাম</th>
            <th>সংক্ষিপ্ত নাম</th>
            <th>মোবাইল</th>
            <th>ক্রম</th>
            <th>অবস্থা</th>
            <th class="d-print-none">নিয়ন্ত্রণ</th>
        </tr>
    </thead>
    {% if object_list %}
    <tbody>
        {% for object,sln in object_list|zip %}
        <tr {% if not object.active %}class='text-muted'{% endif %}>
            <td>{{ sln|e2b_digit }}</td>
            <td class="text-start">{{object}}</td>
            <td class="text-start">{% if object.short_name %}{{object.short_name}}{% endif %}</td>
            <td>{% if object.mobile %}{{object.mobile}}{% else %}-{% endif %}</td>
            <td>{{object.serial|e2b_digit}}</td>
            <td class='icon-lg'>
                <a href="{% url 'change-cust-status' pk=object.pk %}" class="p-1">
                    {% if object.active %}
                    <i class="bi bi-toggle-on text-primary"></i>
                    {% else %}
                    <i class="bi bi-toggle-off text-secondary"></i>
                    {% endif %}
                </a>
            </td>
            <td class="d-print-none">
                <a href="{% url 'update-customer' pk=object.pk %}" class="p-1"><i class="bi bi-pencil-square text-dark"></i></a>
                <a href="{% url 'delete-customer' pk=object.pk %}" class="p-1"><i class="bi bi-trash text-danger"></i></a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
    {% else %}
    <tfoot>
        <tr>
            <td colspan="6" class="text-seocndary text-center">কোনো ক্রেতা তালিকাভুক্ত করা হয়নি!</td>
        </tr>
    </tfoot>
    {% endif %}
</table>

{% load static %}
<script src="{% static 'form_list.js' %}"></script>

<script>
    function toggleGroup(){
        if ($('#id_cust_type').val() == 'Group'){
            $('#id_group').prop("disabled",false)
        } else {
            $('#id_group').prop("disabled",true)
        }
    }

    $('#id_cust_type').on('change', toggleGroup)
    toggleGroup()
</script>

{% endblock main %}

Customer/templates/Customer/duecollection.html
{% extends 'base.html' %}
{% block title %}বকেয়া আদায়{% endblock title %}
{% block style %}
{% endblock style %}
{% block main %}

{% load bootstrap5 %}
{% load extra_tags %}

{% include "Transaction/daily_transactions/links.html" %}

<table class="table table-striped table-bordered table-sm text-center">
    <caption>
        {% include 'org_name.html' %}
        <h4>বকেয়া আদায় - তারিখঃ {{date|e2b_date}}</h4>
    </caption>
    <thead>
        <tr>
            <th>দেনাদার</th>
            <th>আদায়</th>
            <th>অবশিষ্ট পাওনা</th>
            <th class="d-print-none">নিয়ন্ত্রণ</th>
        </tr>
    </thead>
    {% if object_list %}
    <tbody>
        {% for object in object_list %}
        <tr>
            <td class="text-start">{{object.customer.name}}</td>
            <td class="text-start">{{object.amount|format_currency}}</td>
            <td class="text-end">{{object.remaining_due|format_currency}}</td>
            <td class='nowrap d-print-none'>
                <a href="{% url 'update-duecollection' date=date pk=object.pk %}" class="btn btn-sm btn-light py-0">
                    <i class="bi bi-pencil-square"></i>
                </a>
                <a href="{% url 'delete-duecollection' date=date pk=object.pk %}">
                    <i class="bi bi-trash text-danger"></i>
                </a>
            </td>
        </tr>
        {% endfor %}
        <tr>
            <th class='text-end'>সর্বমোট</th>
            <th>{{total|format_currency}}</th>
            <th></th>
            <th class="d-print-none"></th>
        </tr>
    </tbody>
    {% endif %}
    <tfoot class='border d-print-none'>
        <form method="post" id="form">
            {% csrf_token %}
            <tr class='text-start'><th>ক্রেতা যুক্ত করুন</th></tr>
            <tr class='eng'>
                <td>{% bootstrap_field form.customer show_label=False%}</td>
                <td>{% bootstrap_field form.amount show_label=False%}</td>
                <td class='nowrap pb-4'>
                    <button type="submit" class="btn btn-sm btn-success py-0 rounded-0">
                        <i class="bi bi-check-lg" style="font-size:1.5rem"></i>
                    </button>
                    <a href="{% url "create-duecollection" date=date %}" class="btn btn-sm btn-light py-0 rounded-0">
                        <i class="bi bi-x text-danger" style="font-size:1.5rem"></i>
                    </a>
                </td>
            </tr>
        </form>
    </tfoot>
</table>

{% endblock main %}

Customer/templates/Customer/duesell.html
{% extends 'base.html' %}
{% block title %}বকেয়া বিক্রয়{% endblock title %}
{% block style %}
<style>
    .form-control, .input-group-text {
        border-radius: 0;
    }
</style>
{% endblock style %}
{% block main %}

{% load bootstrap5 %}
{% load extra_tags %}

{% include "Transaction/daily_transactions/links.html" %}

<table class='table table-striped table-bordered table-sm text-center'>
    <caption>
        {% include 'org_name.html' %}
        <h4>বকেয়া বিক্রয় - তারিখঃ {{date|e2b_date}}</h4>
    </caption>
    <thead>
        <tr>
            <th>ক্রেতার নাম</th> 
            <th>মালের নাম</th> 
            <th colspan='3'>পরিমান <i class='bi bi-x-lg'></i> দর</th> 
            <th>=</th>
            <th>মোট</th>
            <th class="d-print-none">নিয়ন্ত্রণ</th>
        </tr>
    </thead>
    {% if object_list %}
    <tbody>
        {% for object in object_list %}
        <tr>
            <td class='text-start'>{{object.customer}}</td>
            <td class='text-start'>
                {% if object.product.packaged %}
                <span class='eng'>{{object.product.name}}</span> {{object.product.capacity|format_num}} লিটার
                {% else %}
                {{object.product.name}}
                {% endif %}
            </td> 
            <td colspan='3' class='text-end'>
                {{object.quantity|format_num}} {{object.product.unit}}
                <i class='bi bi-x-lg'></i>
                {{object.selling_rate.amount|format_currency}}
            </td>
            <td>=</td>
            <td class='text-end nowrap'>{{object.price|format_currency}}</td>
            <td class='nowrap d-print-none'>
                <a href="{% url 'update-duesell' date=date pk=object.pk %}" class="btn btn-sm btn-light py-0">
                    <i class="bi bi-pencil-square"></i>
                </a>
                <a href="{% url 'delete-duesell' date=date pk=object.pk %}">
                    <i class="bi bi-trash text-danger"></i>
                </a>
            </td>
        </tr>
        {% endfor %}
        <tr>
            <th colspan='5' class='text-end'>সর্বমোট</th>
            <th>=</th>
            <th class='nowrap'>{{total|format_currency}}</th>
            <th class="d-print-none"></th>
        </tr>
    </tbody>
    {% endif %}
    <tfoot class='border d-print-none'>
        <form method="post" id="form">
            {% csrf_token %}
            <tr class='text-start'><th>বিক্রয় যুক্ত করুন</th></tr>
            <tr class='eng'>
                <td>{% bootstrap_field form.customer show_label=False%}</td>
                <td>{% bootstrap_field form.product show_label=False%}</td>
                <td>{% bootstrap_field form.quantity show_label=False%}</td>
                <td class='pb-4'><i class='bi bi-x-lg'></i></td>
                <td style="width:25%">
                    {% bootstrap_field form.selling_rate show_label=False addon_after="<span class='bangla'>টাকা</span>" %}
                </td>
                <td class='pb-4'>=</td>
                <td class='nowrap pb-4'>
                    {% comment %} {% bootstrap_field form.price show_label=False addon_after="<span class='bangla'>টাকা</span>" %} {% endcomment %}
                    <label><span id="price_display">0</span> <span class="bangla">টাকা</span></label>
                </td>
                <td class='nowrap pb-4'>
                    <button type="submit" class="btn btn-sm btn-success py-0 rounded-0">
                        <i class="bi bi-check-lg" style="font-size:1.5rem"></i>
                    </button>
                    <a href="{% url "create-duesell" date=date %}" class="btn btn-sm btn-light py-0 rounded-0">
                        <i class="bi bi-x text-danger" style="font-size:1.5rem"></i>
                    </a>
                </td>
            </tr>
        </form>
    </tfoot>
</table>

{% load static %}
<script src="{% static 'purchase_sell.js' %}"></script>

{% endblock main %}