FillingStation/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
# import debug_toolbar

from .views import HomeView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('Account.urls')),
    path('settings/', include("Core.urls")),
    path('', HomeView.as_view(), name="home"), # Currently redirects to 'daily-transactions'
    path('transactions/', include("Transaction.urls")),
    path('ledgers/', include("Ledger.urls")),
    path('loan/', include("Loan.urls")),
    path('customer/', include("Customer.urls")),
    path('income-expenditure/', include("IncomeExpenditure.urls")),
    path('owner/', include("Owner.urls")),
    path('product/', include("Product.urls")),
    path('documentation/', include("Documentation.urls")),
]

if settings.DEBUG:
    # urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]
    
    # Serving static files during development (automatically does this)
    # If you don’t have django.contrib.staticfiles in INSTALLED_APPS
    # urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

    # Serving files uploaded by a user during development
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Loan/urls.py
from django.urls import path, register_converter, include
from Core.converters import DateConverter
register_converter(DateConverter, 'date')

from .views import (
    LoanView, BorrowedLoanDetailView, LendedLoanDetailView,
    LenderView, LenderUpdateView, 
    BorrowerView, BorrowerUpdateView,
    BorrowLoanCreateView, BorrowLoanUpdateView, BorrowLoanDeleteView,
    RefundBorrowedLoanCreateView, RefundBorrowedLoanUpdateView, RefundBorrowedLoanDeleteView,
    LendLoanCreateView, LendLoanUpdateView, LendLoanDeleteView,
    RefundLendedLoanCreateView, RefundLendedLoanUpdateView, RefundLendedLoanDeleteView,
    )

urlpatterns = [
    path('', LoanView.as_view(), name='loan-dashboard'),
    path('lender/', include([
        path('', LenderView.as_view(), name='lender'),
        path('<int:pk>/', include([
            path('detail/', BorrowedLoanDetailView.as_view(), name='borrowed-loan-detail'),
            path('update/', LenderUpdateView.as_view(), name='update-lender'),
        ])),
    ])),
    
    path('borrower/', include([
        path('', BorrowerView.as_view(), name='borrower'),
        path('<int:pk>/', include([
            path('detail/', LendedLoanDetailView.as_view(), name='lended-loan-detail'),
            path('update/', BorrowerUpdateView.as_view(), name='update-borrower'),
        ])),
    ])),
    path('borrowed-loan/', include([
        path('new/', BorrowLoanCreateView.as_view(), name='create-borrowed-loan'),
        path('<int:loan_pk>/', include([
            path('update/', BorrowLoanUpdateView.as_view(), name='update-borrowed-loan'),
            path('delete/', BorrowLoanDeleteView.as_view(), name='delete-borrowed-loan'),
            path('refund/', include([
                path('new/', RefundBorrowedLoanCreateView.as_view(), name='create-refund-borrowed-loan'),
                path('<int:pk>/', include([
                    path('update/', RefundBorrowedLoanUpdateView.as_view(), name='update-refund-borrowed-loan'),
                    path('delete/', RefundBorrowedLoanDeleteView.as_view(), name='delete-refund-borrowed-loan'),
                ])),
            ])),
        ])),
    ])),
    
    path('lended-loan/', include([
        path('new/', LendLoanCreateView.as_view(), name='create-lended-loan'),
        path('<int:loan_pk>/', include([
            path('update/', LendLoanUpdateView.as_view(), name='update-lended-loan'),
            path('delete/', LendLoanDeleteView.as_view(), name='delete-lended-loan'),
            path('refund/', include([
                path('new/', RefundLendedLoanCreateView.as_view(), name='create-refund-lended-loan'),
                path('<int:pk>/', include([
                    path('update/', RefundLendedLoanUpdateView.as_view(), name='update-refund-lended-loan'),
                    path('delete/', RefundLendedLoanDeleteView.as_view(), name='delete-refund-lended-loan'),
                ])),
            ])),
        ])),
    ])),
]

Transaction/urls.py
from django.urls import path, register_converter, include
from Core.converters import DateConverter
register_converter(DateConverter, 'date')

from . import views

urlpatterns = [
    path('', views.DailyTransactionView.as_view(), name='daily-transactions'),
    path('<date:date>/', views.DailyTransactionView.as_view(), name='daily-transactions'),
    path('save-cashbalance/<date:date>:<str:amount>/', views.SaveDailyCashBalanceView.as_view(), name='save-daily-cashbalance'),

    # Cashbalance
    path('cashbalance/', include([
        path('list/', views.CashBalanceListView.as_view(), name="cashbalance-list"),
        path('control/', views.CashBalanceControlView.as_view(), name="cashbalance-control"),
        path('new/<date:date>/', views.CashBalanceCreateView.as_view(), name="create-cashbalance"),
        path('<int:pk>/update/', views.CashBalanceUpdateView.as_view(), name="update-cashbalance"),
        path('<int:pk>/delete/', views.CashBalanceDeleteView.as_view(), name="delete-cashbalance"),
    ])),
]

Transaction/models.py
from django.db import models
from django.utils import timezone
import datetime
from django.urls import reverse

# Create your models here.
class CashBalance(models.Model):
    date = models.DateField(default=timezone.now, unique=True, verbose_name="তারিখ")
    amount = models.FloatField(null=True, blank=False, verbose_name="পরিমাণ")
    
    class Meta:
        ordering = ['-date']
        get_latest_by = 'date'
    
    @property
    def is_first(self):
        try:
            return self == self.__class__.objects.earliest()
        except self.__class__.DoesNotExist:
            return False
    
    @property
    def is_last(self):
        try:
            return self == self.__class__.objects.latest()
        except self.__class__.DoesNotExist:
            return False

    def __str__(self):
        return f"{self.date} - {self.amount}"
    
    def get_absolute_url(self):
        next_day = self.date + datetime.timedelta(days=1)
        return reverse('daily-transactions', kwargs={'date':next_day})

    # def save(self):
    #     if not self.date:
    #         prev = CashBalance.objects.latest()
    #         self.date = next_day(prev)
    #     return super().save()

Transaction/forms.py
from django import forms
from datetime import date
from .models import CashBalance
from Core.functions import year_choices
from .functions import first_balance_date

class CashBalanceForm(forms.ModelForm):

    class Meta:
        model = CashBalance
        fields = '__all__'
        widgets = {
            'date': forms.SelectDateWidget(years=year_choices())
        }

# DailyTransactionView
class CashBalanceForm2(forms.ModelForm):
    # balance_form = forms.BooleanField(widget=forms.HiddenInput,initial=True)
    balance_cf = forms.FloatField(widget=forms.HiddenInput)

    class Meta:
        model = CashBalance
        fields = ['amount','balance_cf']
        # widgets = {
        #     'date': forms.HiddenInput(attrs={'name':'next_date'}),
        #     'amount': forms.HiddenInput()
        # }

# Multiple Action
class CashBalanceControlForm(forms.Form):
    balance_date = first_balance_date()
    if not balance_date: balance_date = date.today()

    from_date = forms.DateField(label="তারিখ (হতে)",
        widget=forms.SelectDateWidget( years=range(balance_date.year, date.today().year+2)))
    to_date = forms.DateField(label="তারিখ (পর্যন্ত)",
        widget=forms.SelectDateWidget(years=range(balance_date.year, date.today().year+2)))
    action = forms.ChoiceField(choices=[('save','Save'),('delete','Delete')])

Product/views/purchase_sell.py
from django.shortcuts import redirect
from django.contrib import messages
from django.core.exceptions import ValidationError
from django.views.generic.edit import DeleteView, CreateView, UpdateView
from django.views.generic import ListView
from Core.mixins import RedirectMixin
from Product.models import ConsumeStock
from django.db.models import Sum
from django.urls import reverse_lazy

from Transaction.functions import last_balance_date
from Core.mixins import RedirectMixin
from Product.models import Purchase, Sell
from Product.forms import SellForm, PurchaseForm    

class StockDeleteView(RedirectMixin, DeleteView):
    """
    Custom DeleteView that prevents deletion of objects if they have associated consumed stock.
    """
    template_name = 'delete.html'

    def get(self, request, *args, **kwargs):
        self.check_stock_consumption()
        self.delete(request, *args, **kwargs)
        return redirect(self.get_success_url())
        # try:
        #     # Run the consumption check before deletion
        # except ValidationError as e:
        #     # Handle the error by redirecting back and displaying a message
        #     messages.error(request, str(e))

    def check_stock_consumption(self):
        """
        Checks if any stock related to the instance has been consumed.
        """
        # Assuming the model has a 'stock' or similar relationship to Stock model
        stock_related = self.get_object().stock_set.all()
        for stock in stock_related:
            # If any consumption exists for the stock, raise an error
            if ConsumeStock.objects.filter(stock=stock).exists():
                raise ValidationError("This stock has been consumed and cannot be deleted.")

    def get_success_url(self):
        # Define the URL to redirect to upon successful deletion
        return self.success_url or '/'

# Purchase
class BasePurchaseSellView(RedirectMixin, ListView):
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['date'] = self.kwargs['date']
        qs = self.get_queryset()
        context['total'] = qs.aggregate(Sum('price'))['price__sum'] if qs else 0
        return context
    
    def get_queryset(self):
        return self.model.objects.filter(date=self.kwargs['date'])

class PurchaseCreateView(CreateView, BasePurchaseSellView):
    model = Purchase
    form_class = PurchaseForm
    template_name = 'Product/purchase.html'

class PurchaseUpdateView(UpdateView, BasePurchaseSellView):
    model = Purchase
    form_class = PurchaseForm
    template_name = 'Product/purchase.html'

class PurchaseDeleteView(StockDeleteView):
    model = Purchase

    def get_success_url(self):
        return reverse_lazy('create-purchase', kwargs={'date':self.kwargs['date']})

class SellCreateView(CreateView, BasePurchaseSellView):
    model = Sell
    form_class = SellForm
    template_name = 'Product/sell.html'

class SellUpdateView(UpdateView, BasePurchaseSellView):
    model = Sell
    form_class = SellForm
    template_name = 'Product/sell.html'

class SellDeleteView(DeleteView):
    model = Sell

    def get(self, request, *args, **kwargs):
        self.delete(request)
        return redirect(self.get_success_url())

    def get_success_url(self):
        return reverse_lazy('create-sell', kwargs={'date':self.kwargs['date']})

Transaction/templates/Transaction/daily_transactions/cash.html
{% load extra_tags %}
{% load bootstrap5 %}

<div class="row">
    <div class="col-12">
        <h4 class="text-center">নগদান হিসাব</h4>
    </div>
    <div class="col-6">
        <table class="table table-sm table-bordered table-striped text-end">
            <thead>
                <tr class="text-center">
                    <th>ডেবিট পক্ষ</th>
                    <th>টাকা</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <th class="text-start">প্রারম্ভিক হাতে নগদ</th>
                    <th>{{balance_bf|format_currency}}</th>
                </tr>
                {% if sells %}
                <tr>
                    <td>
                        <div class="row">
                            <div class="col-6 text-start">বিক্রয়</div>
                            <div class="col-6">{{total_sell|format_currency}}</div>
                            {% if duesells %}
                            <div class="col-6 text-start">বাদঃ বকেয়া বিক্রয়</div>
                            <div class="col-6">{{total_duesell|neg|format_currency}}</div>
                            {% endif %}
                        </div>
                    </td>
                    <td class="align-bottom">{{cash_sell|format_currency}}</td>
                </tr>
                {% endif %}
                {% if incomes %}
                <tr>
                    <td class="text-start">মোট আয়</td>
                    <td class="nowrap">{{total_income|format_currency}}</td>
                </tr>
                {% endif %}
                {% if duecollections %}
                <tr>
                    <td class="text-start">বকেয়া আদায়</td>
                    <td class="nowrap">{{total_duecollection|format_currency}}</td>
                </tr>
                {% endif %}
                {% if investments %}
                <tr>
                    <td class="text-start">অতিরিক্ত মূলধন</td>
                    <td class="nowrap">{{total_investments|format_currency}}</td>
                </tr>
                {% endif %}
                {% if borrowed_loans %}
                <tr>
                    <td class="text-start">হাওলাদ গ্রহণ</td>
                    <td class="nowrap">{{total_borrowed_loan|format_currency}}</td>
                </tr>
                {% endif %}
                {% if refund_lended_loans %}
                <tr>
                    <td class="text-start">প্রদত্ত হাওলাদ ফেরত</td>
                    <td class="nowrap">{{total_refund_lended_loan|format_currency}}</td>
                </tr>
                {% endif %}
            </tbody>
            <tfoot>
                <tr>
                    <th>মোট</th>
                    <th class="nowrap">{{total_debit|format_currency}}</th>
                </tr>
            </tfoot>
        </table>
    </div>
    
    <div class="col-6">
        <table class="table table-sm table-bordered table-striped text-end">
            <thead>
                <tr class="text-center">
                    <th>ক্রেডিট পক্ষ</th>
                    <th>টাকা</th>
                </tr>
            </thead>
            <tbody>
                {% if purchases %}
                <tr>
                    <td class="text-start">ক্রয়</td>
                    <td class="nowrap">{{total_purchase|format_currency}}</td>
                </tr>
                {% endif %}
                {% if expenditures %}
                <tr>
                    <td class="text-start">মোট ব্যয়</td>
                    <td class="nowrap">{{total_expenditure|format_currency}}</td>
                </tr>
                {% endif %}
                {% if withdraws %}
                <tr>
                    <td class="text-start">উত্তোলন</td>
                    <td class="nowrap">{{total_withdraw|format_currency}}</td>
                </tr>
                {% endif %}
                {% if lended_loans %}
                <tr>
                    <td class="text-start">হাওলাদ প্রদান</td>
                    <td class="nowrap">{{total_lended_loan|format_currency}}</td>
                </tr>
                {% endif %}
                {% if refund_borrowed_loans %}
                <tr>
                    <td class="text-start">গৃহীত হাওলাদ পরিশোধ</td>
                    <td class="nowrap">{{total_refund_borrowed_loan|format_currency}}</td>
                </tr>
                {% endif %}
                <tr>
                    <th class="text-start">সমাপনী হাতে নগদ</th>
                    <th>
                        {% if saved_balance_cf %}
                            {{saved_balance_cf|format_currency}}
                        {% else %}
                            {{balance_cf|format_currency}}
                        {% endif %}
                    </th>
                </tr>
            </tbody>
            <tfoot>
                <tr>
                    <th>মোট</th>
                    <th class="nowrap">{{total_credit|format_currency}}</th>
                </tr>
            </tfoot>
        </table>
        {% if can_change %}
        <!-- ব্যালেন্স সমন্বয়-->
        <table class="table table-sm table-bordered table-striped d-print-none">
            <caption>
                <h5>ব্যালেন্স সমন্বয়</h5>
            </caption>
            <tbody>
                <tr>
                    <th>সমাপনী হাতে নগদ</th>
                    <th>
                        {{saved_balance_cf}}
                        <form method="post" class="eng">
                            {% csrf_token %}
                            {% bootstrap_form balance_form show_label=False %}
                            <div id='adjust_amount' class='bangla'></div>
                            <button type="submit" class='btn btn-primary'>Save</button>
                        </form>
                    </th>
                </tr>
            </tbody>
        </table>
        {% endif %}
    </div>
</div>

<script>
    function getAdjusted(){
        let cash = $("#id_amount").val()
        let balance_cf = {{balance_cf}}
        let text = ""
        if (balance_cf < cash){
            text ="আয় - বিবিধ : ক্যাশ বাক্সে উদ্ধ্বৃত "
        } else if (balance_cf > cash) {
            text = "ব্যয় - বিবিধ : ক্যাশ বাক্সে ঘাটতি "
        }
        let balance = Math.abs((cash-balance_cf).toFixed(2))
        $('#adjust_amount').html(text + balance)
    }
    $('#id_amount').on({
       // change: getAdjusted, 
        keyup: getAdjusted
    })
    getAdjusted()
</script>

Transaction/templates/Transaction/daily_transactions/due_collection.html
{% load extra_tags %}

{% if duecollections %}
<table class="table table-sm table-bordered table-striped text-end">
    <caption>
        <h5>বকেয়া আদায়</h5>
    </caption>
    <thead>
        <tr class="text-center">
            <th>দেনাদার</th>
            <th>টাকা</th>
        </tr>
    </thead>
    <tbody>
        {% for obj in duecollections %}
        <tr>
            <td class="text-start">{{obj.customer}}</td>
            <td class="nowrap">{{obj.amount|format_currency}}</td>
        </tr>
        {% endfor %}
    </tbody>
    <tfoot>
        <tr>
            <th>মোট আদায়</th>
            <th class="nowrap">{{total_duecollection|format_currency}}</th>
        </tr>
    </tfoot>
</table>
{% endif %}

Transaction/templates/Transaction/daily_transactions/due_sell.html
{% load extra_tags %}

{% if duesells %}
<table class="table table-sm table-bordered table-striped text-end">
    <caption>
        <h5>বাকি বিক্রয়</h5>
    </caption>
    <thead>
        <tr class="text-center">
            <th>দেনাদার</th>
            <th>বিবরণ</th>
            <th>মোট</th>
        </tr>
    </thead>
    <tbody>
        {% for obj in duesells %}
        <tr>
            <td class="text-start">{{obj.customer}}</td>
            <td> 
                {% for duesell in obj.due_sells %}
                <div class="text-start">
                    {{duesell.product.to_html}} : 
                    {{duesell.quantity|format_num:-3}} {{duesell.product.unit}} &times;
                    {{duesell.selling_rate.amount|format_currency:-2}} =
                    {{duesell.price|format_currency:-2}}
                </div>
                {% endfor %}
            </td>
            <td class="text-end align-middle nowrap">{{obj.cust_total|format_currency}}</td>
        </tr>
        {% endfor %}
    </tbody>
    <tfoot>
        <tr>
            <th colspan="2">মোট বাকি বিক্রয়</th>
            <th class="nowrap">{{total_duesell|format_currency}}</th>
        </tr>
    </tfoot>
</table>
{% endif %}

Transaction/templates/Transaction/daily_transactions/inc_exp.html
{% load extra_tags %}

{% if object_list %}
<table class="table table-sm table-bordered table-striped">
    <caption>
        <h5>{{name}}</h5>
    </caption>
    <thead>
        <tr class="text-center">
            <th>বিবরণ</th>
            <th>টাকা</th>
        </tr>
    </thead>
    <tbody>
        {% for obj in object_list %}
        <tr>
            <td>{{obj.group.name}} : {{obj.detail|skip_none}}</td>
            <td class="text-end">{{obj.amount|format_currency}}</td>
        </tr>
        {% endfor %}
    </tbody>
    <tfoot>
        <tr class="text-end">
            <th>মোট {{name}}</th>
            <th>{{total|format_currency}}</th>
        </tr>
    </tfoot>
</table>
{% endif %}

Transaction/templates/Transaction/daily_transactions/investment_withdraw.html
{% load extra_tags %}

{% if object_list %}
<table class="table table-sm table-bordered table-striped text-end">
    <caption>
        <h5>{{name}}</h5>
    </caption>
    <thead>
        <tr class="text-center">
            <th>মালিকের নাম</th>
            <th>বিবরণ</th>
            <th>টাকা</th>
        </tr>
    </thead>
    <tbody>
        {% for obj in object_list %}
        <tr>
            <td class="text-start">{{obj.owner}}</td>
            <td class="text-start">{{obj.detail|skip_none}}</td>
            <td class="nowrap">{{obj.amount|format_currency}}</td>
        </tr>
        {% endfor %}
    </tbody>
    <tfoot>
        <tr>
            <th colspan="2">মোট {{name}}</th>
            <th class="nowrap">{{total|format_currency}}</th>
        </tr>
    </tfoot>
</table>
{% endif %}

Transaction/templates/Transaction/daily_transactions/links.html
{% load extra_tags %}

<div class="d-print-none mb-2">
    {% if pattern_name != 'daily-transactions' %}
        <a href="{% url 'daily-transactions' date %}" class="btn btn-light">
            <i class="bi bi-chevron-left"></i> দৈনিক লেনদেন
        </a>
    {% endif %}

    <a class="btn btn-sm btn-outline-primary" href="{% url 'create-purchase' date %}">ক্রয়</a>
    <a class="btn btn-sm btn-outline-primary" href="{% url 'create-sell' date %}">বিক্রয়</a>
    <a class="btn btn-sm btn-outline-primary" href="{% url 'create-duesell' date %}">বাকি বিক্রয়</a>
    <a class="btn btn-sm btn-outline-primary" href="{% url 'create-duecollection' date %}">বকেয়া আদায়</a>
    <a class="btn btn-sm btn-outline-primary" href="{% url 'create-income' date %}">আয়</a>
    <a class="btn btn-sm btn-outline-primary" href="{% url 'create-expenditure' date %}">ব্যয়</a>
    <a class="btn btn-sm btn-outline-primary" href="{% url 'create-withdraw' date %}">উত্তোলন</a>
    <a class="btn btn-sm btn-outline-primary" href="{% url 'create-investment' date %}">অতিরিক্ত মূলধন</a>
</div>

Transaction/templates/Transaction/daily_transactions/loan_in.html
{% load extra_tags %}

{% if borrowed_loans %}
<table class="table table-sm table-bordered table-striped text-end">
    <caption>
        <h5>হাওলাদ গ্রহণ</h5>
    </caption>
    <thead>
        <tr class="text-center">
            <th>হাওলাদ দাতা</th>
            <th>টাকা</th>
        </tr>
    </thead>
    <tbody>
        {% for loan in borrowed_loans %}
        <tr>
            <td>{{loan.lender.name}}</td>
            <td class="text-end nowrap">{{loan.amount|format_currency}}</td>
        </tr>
        {% endfor %}
    </tbody>
    <tfoot>
        <tr>
            <th>মোট গৃহীত হাওলাদ</th>
            <th class="nowrap">{{total_borrowed_loan|format_currency}}</th>
        </tr>
    </tfoot>
</table>
{% endif %}

{% if refund_lended_loans %}
<table class="table table-sm table-bordered table-striped text-end">
    <caption>
        <h5>প্রদত্ত হাওলাদ ফেরত</h5>
    </caption>
    <thead>
        <tr class="text-center">
            <th>হাওলাদ দাতা</th>
            <th>টাকা</th>
        </tr>
    </thead>
    <tbody>
        {% for refund in refund_lended_loans %}
        <tr>
            <td colspan="3">প্রদত্ত হাওলাদ ফেরত - {{refund.loan.borrower.name}}</td>
            <td class="text-end nowrap">{{refund.amount|format_currency}}</td>
        </tr>
        {% endfor %}
    </tbody>
    <tfoot>
        <tr>
            <th>মোট ফেরত</th>
            <th class="nowrap">{{total_refund_lended_loan|format_currency}}</th>
        </tr>
    </tfoot>
</table>
{% endif %}

Transaction/templates/Transaction/daily_transactions/loan_out.html
{% load extra_tags %}

{% if refund_borrowed_loans %}
<table class="table table-sm table-bordered table-striped text-end">
    <caption>
        <h5>গৃহীত হাওলাদ পরিশোধ</h5>
    </caption>
    <thead>
        <tr class="text-center">
            <th>হাওলাদ দাতা</th>
            <th>টাকা</th>
        </tr>
    </thead>
    <tbody>
        {% for refund in refund_borrowed_loans %}
        <tr>
            <td>{{refund.loan.lender.name}}</td>
            <td class="text-end nowrap">{{refund.amount|format_currency}}</td>
        </tr>
        {% endfor %}
    </tbody>
    <tfoot>
        <tr>
            <th>মোট পরিশোধ</th>
            <th class="nowrap">{{total_refund_borrowed_loan|format_currency}}</th>
        </tr>
    </tfoot>
</table>
{% endif %}

{% if lended_loans %}
<table class="table table-sm table-bordered table-striped text-end">
    <caption>
        <h5>হাওলাদ প্রদান</h5>
    </caption>
    <thead>
        <tr class="text-center">
            <th>হাওলাদ গ্রহীতা</th>
            <th>টাকা</th>
        </tr>
    </thead>
    <tbody>
        {% for loan in lended_loans %}
        <tr>
            <td>{{loan.borrower.name}}</td>
            <td class="text-end nowrap">{{loan.amount|format_currency}}</td>
        </tr>
        {% endfor %}
    </tbody>
    <tfoot>
        <tr>
            <th>মোট ফেরত</th>
            <th class="nowrap">{{total_lended_loan|format_currency}}</th>
        </tr>
    </tfoot>
</table>
{% endif %}

Transaction/templates/Transaction/daily_transactions/purchase_sell.html
{% load extra_tags %}

{% if object_list %}
<table class="table table-sm table-bordered table-striped text-end">
    <caption>
        <h5>{{name}}</h5>
    </caption>
    <thead>
        <tr class="text-center">
            <th>পণ্যের নাম</th>
            <th>পরিমান &times; দর</th>
            <th>টাকা</th>
        </tr>
    </thead>
    <tbody>
        {% for obj in object_list %}
        <tr>
            <td class="text-start">{{obj.product.to_html}}</td>
            <td>
                {{obj.quantity|format_num:-3}} {{obj.product.unit}} &times;
                {{obj.rate|format_currency}}
            </td>
            <td class="nowrap">{{obj.price|format_currency}}</td>
        </tr>
        {% endfor %}
    </tbody>
    <tfoot>
        <tr>
            <th colspan="2">মোট {{name}}</th>
            <th class="nowrap">{{total|format_currency}}</th>
        </tr>
    </tfoot>
</table>
{% endif %}